dist: xenial

language: php

services:
  - mysql

# Mysql isn't installed on trusty (only client is), so we need to specifically install it
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    # For functional tests
    - COMPOSE_FILE="doc/docker-compose/base-dev.yml:doc/docker-compose/selenium.yml"
    - SYMFONY_ENV=behat
    - SYMFONY_DEBUG=1

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: BEHAT_OPTS="--profile=behat --suite=default --tags='~@broken'"
    - php: 7.1
      env: BEHAT_OPTS="--profile=rest --suite=fullJson --tags='~@broken'"

# test only master and pull requests
branches:
  only:
    - master

before_install:
  - ./bin/.travis/prepare_behat.sh

script:
  - cd "$HOME/build/ezplatform";
  - docker-compose exec --user www-data app sh -c "bin/behat $BEHAT_OPTS"

# disable mail notifications		
notification:		
  email: false
  slack:
    rooms:
      - secure: cfcRhrcOrE/aaY0R8uBR8PDvWOFXf6LUlpnWojy/gdgkHfGIgfqF3e+ROZgkXwe99eRNbFTrtkNfBJbOu41Jz9zy3xYEj+NX3JaKkUT7QgpcvU8a7AAehFMPabF/N5E37hoTDl33efDaXM9y2JDG2ygWnWlm5r1tAcaDpmP2tJI=
    on_success: change
    on_failure: always
    on_pull_requests: false

# reduce depth (history) of git checkout
git:
  depth: 30
