dist: xenial
language: php

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - COMPOSE_FILE="doc/docker/base-dev.yml:doc/docker/selenium.yml"
    - SYMFONY_ENV=behat
    - SYMFONY_DEBUG=1
    - EZPLATFORM_REPO="https://github.com/mnocon/ezplatform.git"

matrix:
  include:
    - php: 7.1
      env: BEHAT_OPTS="--profile=behatbundle"

# test only master and pull requests
branches:
  only:
    - master

before_install:
  - ./bin/.travis/prepare_behat.sh

script:
  - cd "$HOME/build/ezplatform";
  - docker-compose exec --user www-data app sh -c "bin/behat $BEHAT_OPTS"

# disable mail notifications		
notification:		
  email: false
  slack:
    rooms:
      - secure: cfcRhrcOrE/aaY0R8uBR8PDvWOFXf6LUlpnWojy/gdgkHfGIgfqF3e+ROZgkXwe99eRNbFTrtkNfBJbOu41Jz9zy3xYEj+NX3JaKkUT7QgpcvU8a7AAehFMPabF/N5E37hoTDl33efDaXM9y2JDG2ygWnWlm5r1tAcaDpmP2tJI=
    on_success: change
    on_failure: always
    on_pull_requests: false

# reduce depth (history) of git checkout
git:
  depth: 30
