language: php

# run tests on php 5.4 only and let unit / integration tests deal with php differences
php:
  - 5.4

# list of paths/bundle to execute
env:
  global:
    - CONFIG="behat.yml"
  matrix:
      # test behat bundle with demo content
    - CONFIG="vendor/ezsystems/behatbundle/EzSystems/BehatBundle/behat.yml" INSTALL="demoContentNonUniqueDB" PROFILE="default" TEST="behat"
      # test demo with demo content
    - INSTALL="demoContentNonUniqueDB" PROFILE="demo" TEST="content"
      # test REST
    - PROFILE="rest" TEST="fullJson"
    - PROFILE="rest" TEST="fullXml"

# test only master (+ Pull requests)
branches:
  only:
    - master

# Setup system for behat testing
before_script:
  # Change local git repo to be a full one as we will reuse current checkout for composer install below
  - git fetch --unshallow && git checkout -b tmp_travis_branch
  - export BRANCH_BUILD_DIR=$TRAVIS_BUILD_DIR
  - export TRAVIS_BUILD_DIR="$HOME/build/ezplatform"
  - cd "$HOME/build"

  # Checkout meta repo, change the branch and/or remote to use a different ezpublish branch/distro
  - git clone --depth 1 --single-branch --branch master https://github.com/ezsystems/ezplatform.git
  - cd ezplatform

  # Install everything needed for behat testing, using our local branch of this repo
  - ./bin/.travis/setup_from_external_repo.sh $BRANCH_BUILD_DIR "ezsystems/behatbundle:dev-tmp_travis_branch"

# execute behat as the script command
script:
  - php bin/behat -vv --config $CONFIG --profile $PROFILE --suite $TEST

# disable mail notifications
notification:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
