services:
    behatbundle.context_argument_resolver:
        class: EzSystems\BehatBundle\Context\Resolver\AnnotationArgumentResolver
        tags:
            -  { name: context.argument_resolver }

    behatbundle.api.facade.contentfacade:
        class: EzSystems\BehatBundle\API\Facade\ContentFacade

    behatbundle.api.facade.contenttypefacade:
        class: EzSystems\BehatBundle\API\Facade\ContentTypeFacade

    behatbundle.api.facade.rolefacade:
        class: EzSystems\BehatBundle\API\Facade\RoleFacade

    behatbundle.api.facade.userfacade:
        class: EzSystems\BehatBundle\API\Facade\UserFacade
