services:
    _defaults:
            autowire: true

    ezbehatbundle.api.facade.contentfacade:
        class: EzSystems\BehatBundle\API\Facade\ContentFacade

    ezbehatbundle.api.facade.contenttypefacade:
        class: EzSystems\BehatBundle\API\Facade\ContentTypeFacade

    ezbehatbundle.api.facade.rolefacade:
        class: EzSystems\BehatBundle\API\Facade\RoleFacade

    ezbehatbundle.api.facade.userfacade:
        class: EzSystems\BehatBundle\API\Facade\UserFacade

    ezbehatbundle.api.contentdata.contentdatacretor:
        class: EzSystems\BehatBundle\API\ContentData\ContentDataCreator
