services:
    _defaults:
            autowire: true
            public: true

    EzSystems\BehatBundle\:
        resource: '../../../../src/lib/*'

    _instanceof:
        EzSystems\BehatBundle\API\Context\LimitationParser\LimitationParserInterface:
            tags: ['behat_limitation_parser']

        EzSystems\BehatBundle\API\ContentData\FieldTypeData\FieldTypeDataProviderInterface:
            tags: ['behat_fieldtype_data_provider']

    ezbehatbundle.api.facade.contentfacade:
        class: EzSystems\BehatBundle\API\Facade\ContentFacade

    ezbehatbundle.api.facade.contenttypefacade:
        class: EzSystems\BehatBundle\API\Facade\ContentTypeFacade

    ezbehatbundle.api.facade.rolefacade:
        class: EzSystems\BehatBundle\API\Facade\RoleFacade

    ezbehatbundle.api.facade.userfacade:
        class: EzSystems\BehatBundle\API\Facade\UserFacade

    ezbehatbundle.api.facade.languagefacade:
        class: EzSystems\BehatBundle\API\Facade\LanguageFacade
